services:
  nexlink-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexlink-pro-container
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
