import { ApplicationStatus } from "@/src/generated/prisma";
import { Reminder } from "@/components/tables/reminders/columns";

export const mockReminders: Reminder[] = [
  {
    id: 1,
    applicationId: 101,
    companyName: "Google",
    jobTitle: "Senior Software Engineer",
    applicationStatus: "APPLIED" as ApplicationStatus,
    interval: 7,
    expirationDate: new Date("2026-03-15"),
    lastSentAt: new Date("2026-02-10"),
    nextSendAt: new Date("2026-02-17"),
  },
  {
    id: 2,
    applicationId: 102,
    companyName: "Microsoft",
    jobTitle: "Frontend Developer",
    applicationStatus: "WAITING_FOR_INTERVIEW" as ApplicationStatus,
    interval: 3,
    expirationDate: new Date("2026-03-01"),
    lastSentAt: new Date("2026-02-12"),
    nextSendAt: new Date("2026-02-15"),
  },
  {
    id: 3,
    applicationId: 103,
    companyName: "Amazon",
    jobTitle: "Full Stack Developer",
    applicationStatus: "BEING_PROCESSED" as ApplicationStatus,
    interval: 14,
    expirationDate: new Date("2026-04-01"),
    lastSentAt: null,
    nextSendAt: new Date("2026-02-20"),
  },
  {
    id: 4,
    applicationId: 104,
    companyName: "Meta",
    jobTitle: "React Developer",
    applicationStatus: "PENDING" as ApplicationStatus,
    interval: 1,
    expirationDate: new Date("2026-02-28"),
    lastSentAt: new Date("2026-02-18"),
    nextSendAt: new Date("2026-02-19"),
  },
  {
    id: 5,
    applicationId: 105,
    companyName: "Netflix",
    jobTitle: "UI Engineer",
    applicationStatus: "APPLIED" as ApplicationStatus,
    interval: 5,
    expirationDate: null,
    lastSentAt: new Date("2026-02-05"),
    nextSendAt: new Date("2026-02-10"),
  },
];
