export const MOCK_JOBS = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    company: "Vercel",
    location: "Remote",
    date: "2/17/2026",
    url: "https://vercel.com/careers",
    logo: "https://logo.clearbit.com/vercel.com",
  },
  {
    id: "2",
    title: "Full Stack Developer",
    company: "Supabase",
    location: "Singapore / Remote",
    date: "2/16/2026",
    url: "https://supabase.com/careers",
    logo: "https://logo.clearbit.com/supabase.com",
  },
  {
    id: "3",
    title: "Software Engineer (Next.js)",
    company: "Stripe",
    location: "Remote",
    date: "2/16/2026",
    url: "https://stripe.com/jobs",
    logo: "https://logo.clearbit.com/stripe.com",
  },
  {
    id: "4",
    title: "AI Engineer",
    company: "OpenAI",
    location: "San Francisco, CA",
    date: "2/15/2026",
    url: "https://openai.com/careers",
    logo: "https://logo.clearbit.com/openai.com",
  },
  {
    id: "5",
    title: "Product Engineer",
    company: "Linear",
    location: "Remote",
    date: new Date().toLocaleDateString(),
    url: "https://linear.app/careers",
    logo: "https://logo.clearbit.com/linear.app",
  },
  {
    id: "6",
    title: "Backend Engineer (Go)",
    company: "Railway",
    location: "Remote",
    date: new Date().toLocaleDateString(),
    url: "https://railway.app/jobs",
    logo: "https://logo.clearbit.com/railway.app",
  },
  {
    id: "7",
    title: "Solutions Architect",
    company: "Amazon Web Services",
    location: "Seattle, WA / Remote",
    date: "2/14/2026",
    url: "https://amazon.jobs",
    logo: "https://logo.clearbit.com/aws.amazon.com",
  },
  {
    id: "8",
    title: "Frontend Developer",
    company: "Airbnb",
    location: "Remote",
    date: "2/14/2026",
    url: "https://careers.airbnb.com",
    logo: "https://logo.clearbit.com/airbnb.com",
  },
  {
    id: "9",
    title: "DevOps Engineer",
    company: "GitHub",
    location: "Remote",
    date: "2/13/2026",
    url: "https://github.com/about/careers",
    logo: "https://logo.clearbit.com/github.com",
  },
  {
    id: "10",
    title: "Senior React Developer",
    company: "Discord",
    location: "San Francisco / Remote",
    date: "2/13/2026",
    url: "https://discord.com/jobs",
    logo: "https://logo.clearbit.com/discord.com",
  },
  {
    id: "11",
    title: "Full Stack Engineer",
    company: "Clerk",
    location: "Remote",
    date: "2/12/2026",
    url: "https://clerk.com/careers",
    logo: "https://logo.clearbit.com/clerk.com",
  },
  {
    id: "12",
    title: "Engineering Manager",
    company: "PostHog",
    location: "Remote",
    date: "2/12/2026",
    url: "https://posthog.com/careers",
    logo: "https://logo.clearbit.com/posthog.com",
  },
];
